R = ["CVresults_murRegAllPos_jointSegNonRandomSegExtraction",...
    "CVresults_netMurRegAllPos_valStop_overTrain"];

load CVresults_murRegAllPos_jointSegNonRandomSegExtraction.mat


targetType = 'AS';
classThr   = 2;
[predPerf,All] = CV_SinglePosPred_performanceSummary(CVresults,...
                                                  targetType,...
                                                  classThr,...
                                                  HSdata)
mean(predPerf.murPred.eachAA.AS.g2.AUCmat)
                                              %%
                                                             
compactLinModelPresentation(glm{1})
close all
getAUCandPlotROC(All.activ,All.target,'plot',true)

BS_table = bootstrap_perfMetric(All.activ, All.target,...
                                            'thr', -0.2,...
                                            'N_sig',1,...
                                            'scale_AUC',100)