R = ["CVresults_murRegAllPos_jointSegNonRandomSegExtraction",...
    "CVresults_netMurRegAllPos_valStop_overTrain"];

load CVresults_noise_murRegAllPos_jointSegNonRandomSegExtraction.mat

targetType = 'AS';
classThr = 2;
[predPerf,S,All,glm] = CV_VHDpredRiskFacModel_performanceSummary(CVresults,...
                                                  targetType,...
                                                  classThr,...
                                                  HSdata,...
                                                  'murmur_variable','AS_calibrated_murmur')
                                                             
compactLinModelPresentation(glm{1})
close all
getAUCandPlotROC(All.activ,All.target,'plot',true)

BS_table = bootstrap_perfMetric(All.activ, All.target,...
                                            'thr', -0.2,...
                                            'N_sig',1,...
                                            'scale_AUC',100)
                                        
                                        
