%% run cross validation
load nodes_jointSeg_v2.mat
load CVpartitions.mat
load('networksCVnoNoiseDrOutMurRegAllPos_jointSegNonRandomSegExtraction.mat','networks')
close all
saveNetFolder = 'C:\HS-project\scripts\model training and testing\CV training\net temporary storage 2';
[CVresults,AUCmat,p,Xtrain,Ytrain] = cross_validation_allPositions(...
                                    CVpartitions,nodes,Paths,...
                                    'CV_set_indeces',1:8,...
                                    'save_net_folder',saveNetFolder,...
                                    'N_validation_stoppage',7,...
                                    'N_cycleOverlap',2,...
                                    'trainNet',false,...
                                    'getTrainData',true,...
                                    'balanceTrain',false,...
                                    'balanceVal',false,...
                                    'trainOnlyOnClean',false,...
                                    'preTrainedNetworks',networks)
