%% run cross validation
load nodes_jointSeg_v2.mat
load CVpartitions.mat
load('networksCVnoNoiseDrOutMurRegAllPos_jointSegNonRandomSegExtraction.mat','networks')
close all
saveNetFolder = 'C:\HS-project\scripts\model training and testing\CV training\net temporary storage';
[CVresults,AUCmat,p,Xtrain,Ytrain] = cross_validation_allPositions(...
                                    CVpartitions,nodes,Paths,...
                                    'HSdata',HSdata,...
                                    'CV_set_indeces',1:2,...
                                    'save_net_folder',saveNetFolder,...
                                    'N_validation_stoppage',7,...
                                    'trainNet',false,...
                                    'getTrainData',false,...
                                    'preTrainedNetworks',true,...
                                    'balanceTrain',true,...
                                    'balanceVal',false,...
                                    'trainOnlyOnClean',false,...
                                    'target_type','ASgrade',...
                                    'thr_testTarget',2,...
                                    'test_target','ASgrade')
