%% run cross validation
load nodes_jointSeg_v2.mat
load CVpartitions.mat
load("networksCV_noNoise_regAorticOnly_jointSegNonRandomSegExtraction.mat", 'networks')
close all
saveNetFolder = 'C:\HS-project\scripts\model training and testing\CV training\net temporary storage';

[CVresults, AUCmat, p, Xtrain, Ytrain] = cross_validation_allPositions( ...
    CVpartitions, nodes, Paths, ...
    'HSdata', HSdata, ...
    "target_type", "avmeanpg", ...
    "thr_resample", 6, ...
    'test_target', 'ASgrade', ...
    'CV_set_indeces', 2:8, ...
    "aa_indeces", 1, ...
    "MaxEpochs", 80, ...
    'save_net_folder', saveNetFolder, ...
    'N_validation_stoppage', 7, ...
    'N_cycleOverlap', 2, ...
    'trainNet', true, ...
    'getTrainData', true, ...
    'balanceTrain', true, ...
    'balanceVal', true, ...
    'N_segmentsPerAudioDesired', 8)

%% save results
load CVresults_netMurRegAllPos_valStop_SpringerSeg.mat

% CVresults.train = renameField(CVresults.train,'activ','activations');
% CVresults.val = renameField(CVresults.val,'activ','activations');

CVresults.train.J = cell(8, 4);
CVresults.val.J = cell(8, 4);
for i = 1:8
    for j = 1:4
        CVresults.train.J{i, j} = find(CVresults.train.I{i, j});
        CVresults.val.J{i, j} = find(CVresults.val.I{i, j});
    end
end

%%
description = ["25-11-22. Trained on aortic pos. avpgmean.", ...
    "Used joint segmentation. Wanted to compare against AS prediction", ...
    "when I trained on murmurs instead."];
fileName = 'CVresults_noNoise_avmeanpg_regAorticOnly.mat';
settings = p.Results;
save(fileName, 'CVresults', 'description', 'settings')