
trainingDescription = {'Used original springer segmentation.',...
'Adapted number of extracted segments to audio length',...
'training stoppage: 10 succsessive failures to improve',...
'validation loss'...
'max 50 epochs'};

trainingDescription = stackStrings(trainingDescription);
tempStorageFolder = Paths.tempSaveNets;
storageFolder = Paths.savedNets;
fileName = 'networksCVnoNoiseDrOutMurRegAllPos_SpringerSeg.mat';
store_trainedNetsInArray(fileName,storageFolder,tempStorageFolder,trainingDescription)
