x = array2table(1:13,'v',...
    ["pred_AScalibrated","pred_max","pred_sum","pred_maxAP","pred_sumAP",...
     "pred_pos1","pred_pos2","pred_pos3","pred_pos4",...
    "murGrade1","murGrade2","murGrade3","murGrade4",...
    "murGradeMax","murGradeSum","murGradeMaxAP","murGradeSumAP"])